### ISSUE TITLE
Describe in documentation timeouts for outgoing dependencies 

### ISSUE THREAD

**Issue by gawarz** [allegro/envoy-control#170]
Sample configuration:
```
metadata:
  proxy_settings:
    outgoing:
      dependencies:
        - service: "*"
          timeoutPolicy:
            idleTimeout: 400
            requestTimeout: 800
        - service: "slow-service-A"
            timeoutPolicy:
              idleTimeout: 800
              requestTimeout: 1500
```

AC:
* describe idleTimeout, requestTimeout
* describe timeout behaviour for missing configs and config with *
