### ISSUE TITLE
Can the envoy-control control node configuration in JWTFilterTest still be effective

### ISSUE THREAD

**Issue by chaggle** [allegro/envoy-control#442]
like 
```yaml
  private val echoConfig = Echo1EnvoyAuthConfig.copy(
            configOverride = """
            node:
              metadata:
                proxy_settings:
                  outgoing:
                    dependencies:
                      - service: "oauth"
                  incoming:
                    unlistedEndpointsPolicy: blockAndLog
                    endpoints: 
                    - path: '/first-provider-protected'
                      clients: ['echo2']
                      unlistedClientsPolicy: blockAndLog
                      oauth:
                        provider: 'first-provider'
                        verification: offline
                        policy: strict
```
because I found the envoy console is not printing API access logs
